config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'patients#index'
  resources :patients
  resources :locations, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  code       :string(10)
#  name       :string(80)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ApplicationRecord
    validates :name, presence: true , length: { maximum: 80 }
    validates :code, length: { maximum: 10 }
    has_many :patients
end

app/models/patient.rb
# == Schema Information
#
# Table name: patients
#
#  id            :integer          not null, primary key
#  first_name    :string(30)       not null
#  middle_name   :string(10)
#  last_name     :string(30)       not null
#  birth         :datetime
#  gender        :integer
#  status        :integer          not null
#  location_id   :integer          not null
#  viewed_count  :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  delete_status :boolean          default(FALSE)
#
# Indexes
#
#  index_patients_on_location_id  (location_id)
#

class Patient < ApplicationRecord
  validates :first_name, presence: {  message: "#{I18n.t('first_name', scope: [:errors])}"} , length: { maximum: 30, message: "#{I18n.t('first_name_length', scope: [:errors])}" }
  validates :last_name, presence: {  message: "#{I18n.t('last_name', scope: [:errors])}"} , length: { maximum: 30 , message: "#{I18n.t('last_name_length', scope: [:errors])}"}
  validates :middle_name, length: { maximum: 10, message: "#{I18n.t('middle_name', scope: [:errors])}" }
  validates :status, presence: {  message: "#{I18n.t('status', scope: [:errors])}"}
  enum status: {initial: 0, referred: 1, treatment: 2, closed: 3}
  enum gender: [:not_available, :male, :female]
  default_scope { where(delete_status: false) }
  belongs_to :location
  validates :location, presence: { message: "#{I18n.t('location', scope: [:errors])}"}
  scope :on_treatment,  ->{ where(status: 2) }
  def destroy
    self.update_column(:delete_status, true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    session[:local] = params[:local] if params[:local]
    I18n.locale = session[:local] || I18n.default_locale
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_patient, only: [:show, :update, :destroy, :edit]
  before_action :incr_view_count, only: :show

  def new
    @patient = Patient.new
  end

  def index
    @patients = Patient.all.includes(:location)
  end

  def show
  end


  def edit
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patient_path(@patient)
    else
      render 'new'
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path(@patient)
    else
      render 'edit'
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def find_patient
      @patient = Patient.find(params[:id])
    end

    def incr_view_count
      @patient.viewed_count += 1
      @patient.save
    end

    def patient_params
      param = params.require(:patient).permit(:first_name,
                                      :middle_name,
                                      :last_name,
                                      :gender,
                                      :status,
                                      :location_id)
      if params[:birth]
          birth = Date.civil(params[:birth]["birth(1i)"].to_i, params[:birth]["birth(2i)"].to_i, params[:birth]["birth(3i)"].to_i)
          param["birth"] = birth
      end
      param
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patients</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=link_to "English", "#{request.path}?local=en"%>
    <%=link_to "中文", "#{request.path}?local=zh-CN"%>
    <%=link_to t('back_index'), patients_path%>
    <%= yield %>
  </body>
</html>

app/views/locations/show.html.erb
<h1>
  <%=t("location")%>
  <br>
  <%=t("name")%>: <%=@location.name%><br>
  CODE: <%=@location.code%>
</h1>

<%=t("local_patient")%>:
<%=render partial: "patients/patient", collection: @location.patients%>

app/views/patients/_patient.html.erb
<ul>
  <li>
    MR: MR<%="%06d" % patient.id%>
  </li>
  <li>
    <%=t("Fullname")%>: <%= "#{patient.last_name}, #{patient.first_name} #{patient.middle_name}"%>
  </li>
  <li>
      <%=t("Age")%>: <%=Time.now.year - patient.birth.year%>
  </li>
  <li>
      <%=t("Gender")%>: <%=t patient.gender%>
  </li>
  <li>
      <%=t("Status")%>: <%=t patient.status%>
  </li>
  <li>
      <%=t("Location_name")%>: <%=link_to patient.location.name, location_path(patient.location) %>
  </li>
  <li>
    <%=t("Viewed_Count")%>:  <%=patient.viewed_count%>
  </li>
  <li>
    <%=link_to t('show'), patient_path(patient.id)%><br>
    <%=link_to t('edit'), edit_patient_path(patient.id)%> <br>
    <%=link_to t('delete'), patient_path(patient.id), method: :delete%>
  </li>
</ul>

app/views/patients/edit.html.erb
<%= form_for :patient , url: patient_path(@patient), method: :patch  do |f| %>
      <% if @patient.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@patient.errors.count, t('patient_new', scope: [:errors])) %> </h2>
         <ul>
         <% @patient.errors.messages.each do |msg| %>
           <li><%= msg[1][0] %></li>
         <% end %>
         </ul>
       </div>
       <% end %>
       <%= f.label t("first_name") %>:
      <%= f.text_field(:first_name , placeholder:  t("first_name"))%>
      <br>
      <%= f.label t("middle_name") %>:
      <%= f.text_field(:middle_name , placeholder: t("middle_name"))%>
      <br>
      <%= f.label t("last_name") %>:
      <%= f.text_field(:last_name , placeholder:  t("last_name"))%>
      <br>
      <%= f.label t("birth") %>:
      <%= f.date_select :birth , prefix: :birth%>
      <br>
      <%= f.label t("Location_name") %>:
      <%= f.collection_select(:location_id, Location.all, :id, :name) %>
      <br>
      <%= f.label t("Gender") %>:
      <%= f.radio_button :gender, "not_available", :checked => @patient.not_available? ? true:false %>
      <%= f.label t("not_available") %>
      <%= f.radio_button :gender, "male", :checked => @patient.male? ? true:false %>
      <%= f.label t("male") %>
      <%= f.radio_button :gender, "female", :checked => @patient.female? ? true:false %>
      <%= f.label t("female") %>
      <br>
      <% status = [[t('initial'), 'initial'],[t('referred'), 'referred'], [t('treatment'), 'treatment'], [t('closed'), 'closed']] %>
      <%= f.label t("Status") %>:
      <%= f.select(:status, status.collect {|p| [p.first, p.last]}, {:include_blank => false}, :selected => @patient.status)%>
    <p>
      <%= f.submit t("save")%>
    </p>
<% end %>

app/views/patients/index.html.erb
<%=link_to t('new_patient'), new_patient_path%>

  <%=render @patients%>

app/views/patients/new.html.erb
<%= form_for :patient , url: {action: "create"} do |f| %>
    <% if @patient.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@patient.errors.count, t('patient_new', scope: [:errors])) %> </h2>
       <ul>
       <% @patient.errors.messages.each do |msg| %>
         <li><%= msg[1][0] %></li>
       <% end %>
       </ul>
     </div>
     <% end %>
     <%= f.label t("first_name") %>:
    <%= f.text_field(:first_name , placeholder: t("first_name"))%>
    <br>
    <%= f.label t("middle_name") %>:
    <%= f.text_field(:middle_name , placeholder: t("middle_name"))%>
    <br>
    <%= f.label t("last_name") %>:
    <%= f.text_field(:last_name , placeholder: t("last_name"))%>
    <br>
    <%= f.label t("birth") %>:
    <%= f.date_select :birth, prefix: :birth %>
    <br>
    <%= f.label t("Location_name") %>:
    <%= f.collection_select(:location_id, Location.all, :id, :name) %>
    <br>
    <%= f.label t("Gender") %>:
    <%= f.radio_button :gender, "not_available", :checked => true %>
    <%= f.label t("not_available") %>
    <%= f.radio_button :gender, "male" %>
    <%= f.label t("male") %>
    <%= f.radio_button :gender, "female" %>
    <%= f.label t("female") %>
    <br>
    <% status = [[t('initial'), 'initial'],[t('referred'), 'referred'], [t('treatment'), 'treatment'], [t('closed'), 'closed']] %>
    <%= f.label t("Status") %>:
    <%= f.select(:status, status.collect {|p| [p.first, p.last]}, {:include_blank => false})%>
  <p>
    <%= f.submit I18n.t("save")%>
  </p>
<% end %>

app/views/patients/show.html.erb
<%patient= @patient%>
<ul>
  <li>
    MR: MR<%="%06d" % patient.id%>
  </li>
  <li>
    <%=t("Fullname")%>: <%= "#{patient.last_name}, #{patient.first_name} #{patient.middle_name}"%>
  </li>
  <li>
      <%=t("Age")%>: <%=patient.birth.nil? ? 0:(Time.now.year - patient.birth.year)%>
  </li>
  <li>
      <%=t("Gender")%>: <%=t patient.gender%>
  </li>
  <li>
      <%=t("Status")%>: <%=t patient.status%>
  </li>
  <li>
      <%=t("Location_name")%>: <%=link_to patient.location.name, location_path(patient.location) %>
  </li>
  <li>
    <%=t("Viewed_Count")%>:  <%=patient.viewed_count%>
  </li>
</ul>